### ISSUE TITLE
ParaView or Paraview

### ISSUE THREAD

**Issue by sloede** [trixi-framework/ParaViewCatalyst.jl#4]
The visualization tool is [officially](https://en.wikipedia.org/wiki/ParaView) [styled](https://www.paraview.org/) Para**V**iew, i.e., with a capital 'V'. The same spelling can also be found in the Catalyst [docs](https://www.paraview.org/Wiki/ParaView/Catalyst/Overview).

Thus before registering as a package, I suggest to think about whether one would like to be consistent and rename the package to `ParaViewCatalyst.jl`.

Personally, I'm be in favor (since I am a fan of consistency), and I don't think that there will be too much confusion since it has not yet been a registered package.

**Comment by benegee** [comment]
Thanks for pointing this out!
